apiVersion: v1
kind: Service
metadata:
  name: arith
  labels:
    app.kubernetes.io/name: arith
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: arith
