apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arith
  labels:
    app.kubernetes.io/name: arith
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: arith
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
